server:
  port: 9000

spring:
  datasource:
    username: root
    password: aaabbb
    url: jdbc:mysql://localhost:3306/kelvinmall-oms?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: "classpath:/mapper/**/*.xml"
  global-config:
    db-config:
      id-type: auto